---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  children:
    server:
      hosts:
        k3s-server:
          ansible_host: 46.225.134.82
          k3s_role: server
          private_ip: 10.0.1.1
          location: cloud

    workers:
      hosts: {}
      # Uncomment when ready:
      # k3s-worker-01:
      #   ansible_host: 192.168.1.11
      #   location: home
      # k3s-worker-02:
      #   ansible_host: 192.168.1.12
      #   location: home
      # k3s-worker-03:
      #   ansible_host: REPLACE_WITH_HETZNER_CX43_IP
      #   location: cloud
